# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bottles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bottles

pod 'GoogleSignIn'

  target 'BottlesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BottlesUITests' do
    # Pods for testing
  end

end
